name: flutter_chat_demo
description: This is the demo for chat app by Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: 1.1.0
  firebase_auth: 1.1.3
  google_sign_in: 5.0.2
  cloud_firestore:  2.0.0
  fluttertoast: 8.0.6
  image_picker: 0.7.4
  shared_preferences: 2.0.5
  firebase_storage: 8.0.5
  intl: 0.17.0
  firebase_messaging: 9.1.3
  flutter_local_notifications: 5.0.0+4
  photo_view: 0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"